apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployXX
  labels:
    app: autodeployXX
  namespace: namespace-workflow-1714639707549
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployXX
  template:
    metadata:
      labels:
        app: autodeployXX
    spec:
      containers:
        - name: autodeployXX
          image: acrworkflow1714639707549.azurecr.io/image-workflow-1714639707549:latest
          ports:
            - containerPort: 5000