apiVersion: v1
kind: Service
metadata:
  name: autodeployXX
  namespace: namespace-workflow-1714473852678
spec:
  type: LoadBalancer
  selector:
    app: autodeployXX
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000